include Makefile.vars

.PHONY: all install clean

SHELL := bash

STUBDOM_BINDIR=/usr/libexec/xen/boot
VMLINUZ=build/linux/arch/x86/boot/bzImage
ROOTFS_IMG=build/rootfs/stubdom-linux-rootfs

# Stubdom disk content
STUBDOM_DISK_FILE= \
  build/busybox/busybox \
  build/qemu/build/qemu-system-i386 \
  rootfs/init \
  rootfs/qemu-ifup \
  rootfs/qemu-ifdown \
  helpers/add-fd \
  helpers/vchan-socket-proxy

Q=scripts/quilt-wrapper

all: $(VMLINUZ) $(ROOTFS_IMG)

QEMU_OPTIONS=--disable-libusb --audio-drv-list=
QEMU_EXTRA_CFLAGS=
QEMU_EXTRA_LDFLAGS=
FULL_BUILDDEPS=
ROOTFS_NAME=qemu-stubdom-linux-rootfs
KERNEL_NAME=qemu-stubdom-linux-kernel
KERNEL_CONFIG=[0-4][0-9]-*

BUSYBOX_PATCHES := $(shell $Q -l busybox)

build/busybox/.extracted: dl/busybox-$(BUSYBOX_VERSION).tar.bz2
	rm -rf build/busybox
	mkdir -p build/busybox
	tar -C build/busybox --strip-components=1 -xf $<
	touch $@

build/busybox/.patched: build/busybox/.extracted busybox/patches/series $(BUSYBOX_PATCHES)
	[ ! -d build/busybox/.patches ] || $Q -C build/busybox -. pop -a
	rm -rf build/busybox/.patches
	cp -aL busybox/patches build/busybox/.patches
	$Q -C build/busybox -. push -a
	touch $@

build/busybox/config.status: build/busybox/.patched
	cp busybox/busybox.config build/busybox/.config
	yes "" | $(MAKE) -C build/busybox oldconfig
	touch $@

build/busybox/busybox: build/busybox/config.status
	$(MAKE) $(MAKE_PARALLEL) -C build/busybox
	strip --strip-unneeded build/busybox/busybox_unstripped
	mv build/busybox/busybox_unstripped build/busybox/busybox

QEMU_PATCHES := $(shell $Q -l qemu)

build/qemu/.extracted: dl/qemu-$(QEMU_VERSION).tar.xz
	rm -rf build/qemu
	mkdir -p build/qemu
	tar -C build/qemu --strip-components=1 -xf $<
	touch $@

build/qemu/.patched: build/qemu/.extracted qemu/patches/series $(QEMU_PATCHES)
	[ ! -d build/qemu/.patches ] || $Q -C build/qemu -. pop -a
	rm -rf build/qemu/.patches
	cp -aL qemu/patches build/qemu/.patches
	$Q -C build/qemu -. push -a
	touch $@

build/qemu/build/config.status: build/qemu/.patched
	mkdir -p build/qemu/build && cd build/qemu/build && ../configure \
		--without-default-features \
		--target-list=i386-softmmu \
		--enable-xen \
		--enable-xen-pci-passthrough \
		--disable-werror \
		--disable-sdl \
		--disable-kvm \
		--disable-gtk \
		--disable-slirp \
		--enable-pie \
		--disable-docs \
		--disable-vhost-net \
		--disable-spice \
		--disable-guest-agent \
		--disable-smartcard \
		--disable-vnc \
		--disable-spice \
		--enable-trace-backends=log \
		--disable-gnutls \
		--disable-nettle \
		--disable-gcrypt \
		--disable-vte \
		--disable-curses \
		--disable-cocoa \
		--disable-virtfs \
		--disable-brlapi \
		--disable-curl \
		--disable-rdma \
		--disable-vde \
		--disable-netmap \
		--disable-linux-aio \
		--disable-cap-ng \
		--disable-attr \
		--disable-rbd \
		--disable-libiscsi \
		--disable-libnfs \
		--disable-usb-redir \
		--disable-lzo \
		--disable-snappy \
		--disable-bzip2 \
		--enable-seccomp \
		--disable-coroutine-pool \
		--disable-glusterfs \
		--disable-tpm \
		--disable-libssh \
		--disable-numa \
		--disable-qom-cast-debug \
		--disable-virglrenderer \
		--disable-tools \
		--disable-replication \
		--disable-opengl \
		--disable-virglrenderer \
		--disable-tcg \
		--disable-crypto-afalg \
		--disable-live-block-migration \
		--disable-vhost-user \
		--disable-vhost-crypto \
		--disable-vdi \
		--disable-bochs \
		--disable-cloop \
		--disable-dmg \
		--disable-qcow1 \
		--disable-parallels \
		--disable-vvfat \
		--disable-qed \
		--disable-auth-pam \
		--enable-rng-none \
		${QEMU_OPTIONS} \
		--cxx=/non-existent \
		--extra-cflags="-DXEN_PT_LOGGING_ENABLED=1 ${QEMU_EXTRA_CFLAGS}" \
		--extra-ldflags="${QEMU_EXTRA_LDFLAGS}" \
		--prefix=/usr

build/qemu/build/qemu-system-i386: build/qemu/.patched build/qemu/build/config.status
	$(MAKE) $(MAKE_PARALLEL) -C build/qemu/roms seavgabios-{cirrus,stdvga}
	#$(MAKE) $(MAKE_PARALLEL) -C build/qemu/pc-bios/optionrom linuxboot.bin linuxboot_dma.bin
	$(MAKE) $(MAKE_PARALLEL) -C build/qemu/build
	strip --strip-unneeded $@

$(SEABIOS): build/qemu/.patched
	$(MAKE) -C build/qemu/roms build-seabios-config-seabios-256k

LINUX_PATCHES := $(shell $Q -l linux)

build/linux/.extracted: dl/linux-$(LINUX_VERSION).tar
	rm -rf build/linux
	mkdir -p build/linux
	tar -C build/linux --strip-components=1 -xf $<
	touch $@

build/linux/.patched: build/linux/.extracted linux/patches/series $(LINUX_PATCHES)
	[ ! -d build/linux/.patches ] || $Q -C build/linux -. pop -a
	rm -rf build/linux/.patches
	cp -a linux/patches build/linux/.patches
	$Q -C build/linux -. push -a
	touch $@

build/linux/.config: $(sort $(wildcard linux/config/[0-9][0-9]-*)) build/linux/.extracted
	cd build/linux; env -u MAKEFLAGS ./scripts/kconfig/merge_config.sh -n /dev/null ../../linux/config/$(KERNEL_CONFIG)

$(VMLINUZ): build/linux/.patched build/linux/.config
	$(MAKE) $(MAKE_PARALLEL) -C build/linux

helpers/vchan-socket-proxy helpers/add-fd: helpers/vchan-socket-proxy.c helpers/add-fd.c
	$(MAKE) $(MAKE_PARALLEL) -C helpers

DRACUT_INSTALL=/usr/lib/dracut/dracut-install

rootfs/gen: $(DRACUT_INSTALL)

export DRACUT_INSTALL
$(ROOTFS_IMG): rootfs/gen $(STUBDOM_DISK_FILE)
	env -u MAKELEVEL -u MAKEFLAGS -u MFLAGS ./$<

install: $(VMLINUZ) $(ROOTFS_IMG)
	install -D -m 444 $(VMLINUZ) $(DESTDIR)$(STUBDOM_BINDIR)/$(KERNEL_NAME)
	install -D -m 444 $(ROOTFS_IMG) $(DESTDIR)$(STUBDOM_BINDIR)/$(ROOTFS_NAME)

clean:
	rm -rf build
